SES-BE: load docker and added db

diff --git a/.github/workflows/be-build-deploy.yml b/.github/workflows/be-build-deploy.yml
--- a/.github/workflows/be-build-deploy.yml
+++ b/.github/workflows/be-build-deploy.yml
@@ -25,30 +25,25 @@ jobs:
     - name: Deploy to EC2
       run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} << EOF
-            APP_DIR=~/project
+            APP_DIR=~/social-exchange-service
             
             if [ ! -d "\$APP_DIR" ]; then
               mkdir -p "\$APP_DIR"
               git clone https://github.com/SvetlanaShish/social-exchange-service.git "\$APP_DIR"
             fi
-            
+
             cd "\$APP_DIR"
             git pull
-            
-            #Check poetry
-            if ! command -v poetry &> /dev/null
-            then
-              echo "Poetry not found, installing..."
-              curl -sSL https://install.python-poetry.org | python3 -
-              echo "export PATH=\$HOME/.local/bin:\$PATH" >> ~/.bashrc
-              source ~/.bashrc
+
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found, installing..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+              sudo usermod -aG docker $USER
+              rm get-docker.sh
             fi
 
-            cd backend
-            poetry install --no-root
-            
-            lsof -t -i :8080 | xargs -I {}  kill -9 {}
-            poetry run uvicorn app:app --host 0.0.0.0 --port 8080 --reload 
+            docker-compose -f docker-compose.yml up -d --build 
           EOF
 
     
