Update be-build-deploy.yml - added docker

diff --git a/.github/workflows/be-build-deploy.yml b/.github/workflows/be-build-deploy.yml
--- a/.github/workflows/be-build-deploy.yml
+++ b/.github/workflows/be-build-deploy.yml
@@ -43,6 +43,12 @@ jobs:
               rm get-docker.sh
             fi
 
+            if ! command -v docker-compose &> /dev/null; then
+              echo "Docker Compose not found, installing..."
+              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            fi
+
             docker-compose -f docker-compose.yml up -d --build 
           EOF
 
